# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f11871177e56aed6085565d076fbf5eb1e40abd0d2d8df389b142e75651352fabcfe9f14a80ef39fbc37cfa806b0e424283cc775d1279cb5476129b16509294

test:
  secret_key_base: a8a992b0e821425e2e299df19d0b96b827f92e533896da949cfd64a78f61bb707c08195aed71d701aff212739bdd8028d863f7f14503571b8e1eeecdab79f237

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
